version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/electron-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/chrome-extension"
    schedule:
      interval: "weekly"
